- name: Hello World Sample
  hosts: all
  tasks:
    -name: vsftpd package install
     package:
       name: vsftpd
       state: present
       state: enabled
    - name: Installation output
      debug:
        msg: "vsftpd package is installed!"

