---
- name: Hello World Sample
  hosts: all
  ignore_errors: true
  tasks:
  - name: vsftpd package install
    package:
      name: vsftpd
      state: present
  - name: vsftpd service start
    service:
      name: vsftpd
      state: started
      enabled: yes
  - name: Installation output
    debug:
      msg: "vsftpd package is installed!"

